# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Continue"
        Invoke-WebRequest http://raw.github.com/hughparsonage/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary
  - C:\temp\miktex

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - Rscript -e print(as.character(Sys.time()))
  - cd data-raw/miktex
  - unzip miktexsetup-x64.zip
  - miktexsetup --local-package-repository=C:\temp\miktex --package-set=basic download
  - miktexsetup --verbose --local-package-repository=C:\temp\miktex --package-set=essential download
  - (robocopy sources C:\temp\miktex *.tar.lzma) ^& IF %%ERRORLEVEL%% LSS 8 EXIT /B 0
  - Rscript -e "file.copy('sources/moreenum.tar.lzma', 'C:/temp/miktex/moreenum.tar.lzma')"
  - miktexsetup --verbose --local-package-repository=C:\temp\miktex --remote-package-repository=http://ctan.mirrors.hoobly.com/systems/win32/miktex/tm/packages/ install
  #- travis-tool.sh run_tests
  - Rscript -e print(as.character(Sys.time()))

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
