version: 1.0.{build}
image: Visual Studio 2017

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml


install:
  - ps: choco install -y miktex.portable
  - cmd:  refreshenv

build_script:
  - cmd: cd tests\testthat\SchoolFunding
  - cmd: pdflatex -interaction=nonstopmode .\Report.tex
