version: 1.0.{build}
image: Visual Studio 2017

environment:
  global:
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9

install:
  - ps: choco install -y miktex
  - ps: choco update miktex
  - cmd: refreshenv
  - ps: choco install -y r.project
  - ps: $env:Path += ";C:\Program Files\R\R-3.5.0"
  - ps: $env:Path += ";C:\Program Files\R\R-3.5.0\bin"


build_script:
  - cmd: Rscript -e "stys <- dir(pattern = '.sty$', path = 'data-raw/miktex/sty', full.names = TRUE); file.copy(stys, file.path('tests/testthat/SchoolFunding', basename(stys)))"
  - cmd: cd tests\testthat\SchoolFunding
  - ps: wget https://raw.githubusercontent.com/HughParsonage/grattex/master/grattan.cls -Outfile grattan.cls
  - cmd: erase SchoolFunding.bbl
  - cmd: pdflatex -interaction=batchmode SchoolFunding.tex
  - cmd: biber SchoolFunding
  - cmd: pdflatex -interaction=batchmode SchoolFunding.tex
